version: '3'

services:
  prom:
    image: prom/prometheus
    volumes:
      - ./prom.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  pingpong_01: &pingpong
    build: .
    command: "-consul"
    environment:
      - CONSUL_HTTP_ADDR=http://consul-agent-1:8500

  pingpong_02:
    <<: *pingpong

  pingpong_03:
    <<: *pingpong

  slow_cooker_01: &slow-cooker
    image: buoyantio/slow_cooker:latest
    entrypoint: /bin/sh
    command: >
      -c 'sleep 5 && slow_cooker -qps 250 -concurrency 20 -interval 5s -host pingpong http://envoy-simple/pong'

  consul-agent-1: &consul-agent
    image: consul:latest
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"

  rotor:
    image: turbinelabs/rotor:0.17.2
    restart: always
    environment:
      - ROTOR_CMD=consul
      - ROTOR_CONSUL_DC=dc1
      - ROTOR_CONSUL_HOSTPORT=consul-agent-1:8500

  envoy-simple:
    image: turbinelabs/envoy-simple:latest
    restart: always
    environment:
      - ENVOY_XDS_HOST=rotor
      - ENVOY_XDS_PORT=50000